### ISSUE TITLE
Mining Speed / ETA is not Accurate

### ISSUE THREAD

**Issue by FrantzX** [narc0tiq/YARM#127]
How To Fix:

File: resmon.lua
Line: 641
Fix: Change "if delta_ore_since_last_update > 0 then " to "if delta_ore_since_last_update ~= 0 then"

"delta_ore_since_last_update" is always 0 or a negative number, thus this condition is never true.

**Comment by Kingdud** [comment]
While changing this to ~= would have an effect, it wouldn't really be the desired one. In order to actually fix this, we really need to keep a few snapshots, over time, of how many changes happen to the field and how long each change took from the last change. I haven't run a long test yet, but so far, in my own game, my linked change is now showing accurate field rates (the 34m field drained in 34m wall clock time, the 1h15m field drained in 1h15m, etc.) My patch isn't perfect, it needs at least two snapshots of data to produce valid results, so fields that are idle when the new code is rolled out will end up showing nonsense data for their mining rate until they spin up and mine again (the first data snapshot is grabbed automatically from existing variables).

I'll continue to test it in my personal game, but so far, it's working great for me.
