### ISSUE TITLE
Filtered selection

### ISSUE THREAD

**Issue by RabidGuy** [narc0tiq/YARM#137]
With mods, resources are sometimes very crowded and selecting the resources you want can be difficult. Choosing a filter before dragging would allow you to select that resource out of a mix of others.

Without this functionality I often find that YARM just won't select the resource I want or won't select several small pieces of that resource among a larger mix of resources.

**Comment by narc0tiq** [comment]
Keeping in mind that site scanning will happily chase down connected resources as long as you've selected at least one to start recording the site, together with the ability to expand a site after its creation to add any not-sufficiently-connected patches this issue seems to be mostly mitigated already.

I'm also having a hard time imagining the UI to set the filter, though I think that's a solvable problem.

Overall, I think I'm going to close this for now, until a stronger argument to do this comes around.
