### ISSUE TITLE
New Update Version 0.8.206 cant launch server.

### ISSUE THREAD

**Issue by Wolf10K** [narc0tiq/YARM#145]
It fails to load saved data

Factorio reports the save file might be corrupt

**Comment by Wolf10K** [comment]
Unloading the mod, Launching the server, saving then reloading the mod seems to clear it.

**Comment by narc0tiq** [comment]
How weird. I didn't have that happen even when I did some very weird things. Do you still have the "corrupted" save, and could you send it to me? I'm curious if I can figure anything out from it.

**Comment by Wolf10K** [comment]
Yes I have the saves. When I updated it initially it was fine for me but my friend couldnt join. I thought it was the save file size and since we are also using the space exploration modpack I trimmed some of the surfaces down and got the save file size down from 94.2 MB to 70MB. At which point he still couldnt join and I relaunched my game and bam I was unable to load in now either.

1. I have the save I loaded into immediately after updating.
2. The save I made after loading in so my friend could try loading in on a "fresh save" ( i hadnt relaunching yet)
3. The save I made after trimming down the file size, Where he still couldn't join in and which is the save i tried loading into after relaunching.

Here a link to them let me know if it works
https://drive.google.com/drive/folders/1x_U6hVRQX8gbzqPrFErKt2WTtRRRAS0P?usp=sharing

**Comment by narc0tiq** [comment]
Ah, well, sorry, I only have bad news: [Hornwitser's factorio_tools](https://github.com/Hornwitser/factorio_tools), which I was trying to use to read the script data and see what might've been corrupted, is actually not able to read things correctly. It could be that even the 147 file is corrupted, in which case -- do you still have save 146? Can I look at that one? -- but I think more likely the parser is broken so I can't really read the file.

Since the workaround worked and as long as recreating the sites isn't too big a chore, I'll have to leave it like this. Hopefully this was just a one-off and you shouldn't run into this problem again.

**Comment by narc0tiq** [comment]
NB: I'm getting ]more reports of save file corruption](https://mods.factorio.com/mod/YARM/discussion/624a92cb45634948ba15ab5e) so maybe it would be best to revert back to the previous version of YARM. I've taken down 0.8.206 from the mod portal while I investigate some more.

**Comment by wchristian** [comment]
recent developments have superceded this :)
