### ISSUE TITLE
Click/action often "missed" (nothing happens) [multiplayer]

### ISSUE THREAD

**Issue by markheloking** [narc0tiq/YARM#16]
Factorio 0.12.10, Mods: Bobs mods (all), Landfill (2.1.6), RSO (1.4.2), YARM (0.6.23)

Playing multiplayer ([Daniel34's server](http://www.factorioforums.com/forum/viewtopic.php?f=53&t=13579)) often gives the problem that the buttons (the eye and the cross) for interacting with the YARM mod do not respond/don't do anything half the time. You have to press it a multitude of times and only every once in a while will it respond. Not sure if the same behaviour is seen in single player.

**Comment by narc0tiq** [comment]
Thank you for the concise and complete report. This is kind of a nasty one and needs YARM to become more clever (usually something I try to avoid).

What's happening is that every time the GUI updates (to show the current state of the tracked ore sites), all the site listings and their relevant buttons are destroyed and new ones put in their place. Visually this tends to seem static (site recounting updates happen on a different, slower cycle), but the game will tend to cancel your clicks on the buttons because they're being caused by a deleted UI element (which Factorio needs to do to avoid things like the FARL "exit train and crash all the players because you hit Enter" bug). Trying repeatedly will eventually make your click (press and release) happen while the button is still valid, which allows it to go through -- which is why it sometimes works.

I've been thinking about it, off and on, since I first noticed it in my games, and it's not easy. The reason I'm deleting all the GUI elements is to reorder them when needed; the only guaranteed way to avoid it is to stop maintaining the dynamic order by remaining ore percentage and move to something static like when the site was created.

- The first possible solution that comes to mind would be to avoid doing so for sites that haven't moved up or down in the order -- which would also have the nice side-effect of (usually) cancelling your clicks when you hit a site that changed its position while you were clicking it. A possible way to do this would be to keep track of an old copy of the (ordered) site list and comparing the current position we're iterating with the same position in the previous list. If they're identical, nothing needs to change, the button will remain static and function normally.

- Another potential solution would be to add another layer of abstraction: currently the site labels and buttons all contain the site name in their names. If we instead just give them an index from the sorted list, the buttons can be completely static forever, and only the labels ever need change. This makes the buttons remain static except for the very tick when a site is added or deleted, at which point only the last site's buttons need to be created or destroyed. The disadvantage is needing to make sure the sorted list whose indices we're using exactly reflects the visual elements, otherwise you get weirdness like deleting, viewing, or renaming a different site than then one you've clicked on.

- As a stopgap, increasing the time between GUI updates would make it more likely you'll be able to click the button before it gets replaced; going down as far as once every 10 seconds would lead to only occasionally needing to click a button twice when you just happen to hit it at the wrong time. This is by far the easiest fix, but it only cloaks the underlying cause while retaining an intermittent "sometimes I have to click twice before YARM accepts my rename/view/delete requests".


Rest assured, I will continue thinking about the best way to resolve the issue; probably a combination of the first two options will end up being the final fix. In the meantime, give [this in-dev package (direct download: YARM v0.6.24)](http://dev.narc.ro/factorio/mod-packages/YARM_0.6.24.zip) a try -- it changes the GUI update timer to 5 seconds, which should make the cancelled clicks far less common (as per the third option).

**Comment by markheloking** [comment]
I am most in favor of the extra abstraction actually, but I agree that a combination of the first and second option might be better overall as well.

Thanks for maintaining this awesome mod!
