### ISSUE TITLE
Allow adding more entities to an existing site

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#18]
(from @Choumiko, via http://www.factorioforums.com/forum/viewtopic.php?p=112431#p112431)

It should be reasonably trivial to put a site into "add" mode again, whereafter behaviour should be pretty much as expected: smack a correct-type entity to add it and any neighbours, or smack the ground to cancel.

**Comment by Thel89** [comment]
I've been thinking about how to add this. Things I'm fairly sure are needed:
- new button images at the bottom of gui.png (probably just a plus sign, with appropriate shading to match the other buttons)
- another button prototype in prototypes/prototypes.lua
- support for that button in resmon.on_gui_click (and probably a new function like `resmon.on_click.expand_site`)
- support for that button in resmon.update_ui (to add that button under the right conditions)

However, I'm unsure what the new button would actually *do* in the on_click. I'm guessing (based on my understanding of reading the code), it would need to:
- un-submit the ore-site associated with the button we just pushed (i.e. remove it from `force_data`, put it back into `player_data.current_site`)
- set `finalizing_since` to `game.tick` (to reset the timer).

At that point, the player *should* be able to smack the YARM on the ore they want the site expanded to, right?

Other thoughts: because it's in current_site at that point, smacking the YARM on the ground will remove the site from YARM monitoring. That's probably unintuitive behaviour - what should we do if someone tries to expand a site and smacks the YARM on empty ground? I'd say we should probably just submit the site, rather than clearing it.

**Comment by narc0tiq** [comment]
I'd say we should cancel the changes to the site if the player smacks the ground.

Also, you can't remove it from `force_data` -- that would remove it for the other players on your team. Also also, you probably want to reconstruct the overlay showing what ores are already in the site.
