### ISSUE TITLE
[Bug] YARM makes it extremely hard to rename map tags

### ISSUE THREAD

**Issue by 1n5aN1aC** [narc0tiq/YARM#189]
I have narrowed it down to YARM causing this on 2.0.24 w/ SpaceAge.

I add a tag to the map, close the map, and when you open the map up, and click on the tag to rename it, approx. every 2 seconds the tag reverts to the text it was originally.  You are able to change the text if you are fast enough and try enough times, it's just very hard.

I believe this has something to do with the YARM re-drawing it's information in the top right somehow resetting the tag, but I can't figure out how.

**Comment by narc0tiq** [comment]
This might actually count as a Factorio bug -- the issue is not with the YARM HUD but with its map markers; as a workaround, you may turn off "Enable map markers" in the YARM mod settings, but note this disables them for all players (it's a global setting because the markers themselves are per-force).

When YARM updates its own map markers (which it does every time it recounts the sites), it apparently resets the marker rename window even if you're editing a completely unrelated marker (even if it's on a completely different surface!).

**Comment by narc0tiq** [comment]
I have created a report: https://forums.factorio.com/viewtopic.php?f=7&t=124220

**Comment by 1n5aN1aC** [comment]
Devs say it is fixed for next release!

Thanks much for confirming that it's a Factorio bug and getting it reported.
