### ISSUE TITLE
Disconnect between player character and view

### ISSUE THREAD

**Issue by Demosthenexx** [narc0tiq/YARM#32]
Yarm 0.7.15 with Factorio 0.12.29.

In multiplayer environment, monitor a pile of resources. Use "eye" icon to remotely view that pile, then use movement keys to try to pan screen.

Expected outcome: Panning should fail silently.

Actual outcome: Screen moves, immediate and repeated desync. If lucky enough to be able to disable remote view, desyncs stop. Deleting all YARM monitors not always possible, and now control of character is lost.

**Comment by narc0tiq** [comment]
I'm sorry, I can't reproduce this -- using Factorio 0.12.29, a Linux headless server and a Windows client, with YARM 0.7.15, EvoGUI 0.4.14, and no other mods, I cannot move the fake player character when remote-viewing a resource site.

It is possible another mod you have is messing around with the player character definition -- as you can see [in the YARM prototypes](https://github.com/narc0tiq/YARM/blob/96dd2eb30555a8ac3e9cd83b2874c8a1e2c5940c/prototypes/prototypes.lua#L133), the fake player should be unable to move. Can you make your set of mods available?

**Comment by narc0tiq** [comment]
Only semi-relatedly, I'd love to know how this happened:
```
23:31:00 <Demosthenex> crap. so YARM has disconnected my view from my character      
23:31:11 <Demosthenex> i can pan around the map, but not move my char
```

...Which I mention specifically because YARM has code to [prevent you from remote-viewing a site](https://github.com/narc0tiq/YARM/blob/master/resmon.lua#L673) when you're likely to get stuck in the remote view.

---

For future reference, there is a [remote interface function that can reset you back to your character](https://github.com/narc0tiq/YARM/blob/master/remote.lua#L5) -- you can invoke it by typing `/c remote.call("YARM", "reset_player", game.local_player.index)` into the console and pointing your cursor at your player character before hitting Enter. Note that this is a debuggish feature and may let you do crazy things, so try not to misuse it.

**Comment by Demosthenexx** [comment]
I removed every one of my YARM monitors, and then had to reset my character using the mouse selection and lua. It's repeatable. I am on Linux both client and server side though. I just broke it again earlier. To be fair, there's two stages. If I can disable remote viewing during the desync loop, the site I was viewing stays stuck in a viewing state in the list. It was while purging my list of sites that I got completely disconnected. Unfortunately the logging messages only goto the in game chat, I don't see them on the console or the logs.

Mod list:
color-coding_1.0.7.zip       
KS_Power_0.1.1.zip    
Concrete_Lamppost_0.1.0.zip 
Landfill_2.1.7.zip  
rso-mod_1.5.0.zip
fluid-barrel_1.0.0.zip       
Loot-able Rocks_1.0.0.zip  
YARM_0.7.15.zip

**Comment by Demosthenexx** [comment]
We can always discuss on IRC. Feel free to PM.

**Comment by Demosthenexx** [comment]
Oh! While trying to fix it I found the cause of the complete player disconnect. YARM asked me to try and run reset_player, and when I did the camera completely disconnected.

**Comment by narc0tiq** [comment]
Please forgive the slow response, I've found myself otherwise occupied this week-end. In any case, I got my hands on a Linux test machine and, despite some graphical issues (this machine has a crap video card), I still can't reproduce this bug.

When I remote-view a YARM site, I cannot move the fake player character I'm inhabiting.

None of the mods you're referencing should be messing around with YARM, either, so I can't even begin to imagine what's causing this behaviour in your case.

**Comment by Demosthenexx** [comment]
Slow response isn't an issue. You're providing an excellent mod for free! Thank you for investing your time.

As to the reproduction, if we can't reproduce it, let's just close the ticket. Thanks for trying.

**Comment by narc0tiq** [comment]
All right; feel free to reopen if you ever find out what went wrong.

Can I ask you, for the sake of my own curiosity, whether you can reproduce it on your machine, in a new world, with *only* YARM (and, at that, with a fresh download of it, just in case)? You will probably find these useful for faster setup:

```Lua
/c game.always_day = true
/c game.peaceful_mode = true
/c game.local_player.insert{name="resource-monitor"}
```
