### ISSUE TITLE
Support for water wells

### ISSUE THREAD

**Issue by mexmer** [narc0tiq/YARM#42]
In bobs mod there is ground water and lithia water.
Ground water is not that important, since there is usually lake to take water from, but lithia water is important (you need it for batteries).
While most likely this resource cannot be depleted (like oil), it drops output over time (like oil).  I track oil patches for such reason, and want to track lithia water  too.

thanks.

**Comment by narc0tiq** [comment]
It's worth mentioning that the reason you couldn't track these using YARM before is because YARM would raise the error `Unknown resource category: "water"` (because water and lithia water sources are not `basic-fluid`s. I'm sure there's a good reason for this).

As it happens, as of f1aa00b48fd17f235f59c44186cd0738613452ee, this should no longer be a problem. This was released as [v0.7.104](https://github.com/narc0tiq/YARM/releases/tag/v0.7.104) and should be published [in the usual place on the mod portal](https://mods.factorio.com/mods/Narc/YARM/downloads), as well.

Please reopen (with a description of any error encountered) if you still have difficulties tracking Bob's water or lithia water springs in YARM v0.7.104 or higher.

**Comment by mexmer** [comment]
@narc0tiq thanks for response, i will check later with new version.
and yes error it raised was the one you meantioned.

**Comment by mexmer** [comment]
OK, tested last night, looks fine to me, thanks :+1:

**Comment by narc0tiq** [comment]
Glad to hear it! And if you run into any other issues, go right ahead and let me know. Enjoy your resource monitoring :smile:
