### ISSUE TITLE
UI keeps opening

### ISSUE THREAD

**Issue by LennyIndustries** [narc0tiq/YARM#59]
Hi, I have the mod installed (V0.7.108) and when I open a chest, assembler, train (wagon), ... the YARM UI shows up, if I close it and open another thing, it shows up again. Also the config button (the little gear) isn't showing (don't know if it's removed or not).

**Comment by narc0tiq** [comment]
Supposedly, this is something Nexela's Circuit Alerter causes: https://mods.factorio.com/mods/Narc/YARM/discussion/9223 and https://mods.factorio.com/mods/Nexela/CircuitAlerter/discussion/5234

That said, after glancing at the relevant code, I agree with Nexela: it's all set up correctly to hide the expandoed YARM when a relevant event happens and to show it again if it was previous expanded. It's unlikely that `global.player_data[player.index].expandoed` has gotten desynced, because it directly controls whether the expando is opened or not.

And no, the settings button has never existed, except in one picture from the beta. It has yet to be implemented.

---

As there is no code in YARM to open or close the expando when external events occur (I only provide an external API for others to do so), this cannot be a YARM issue.
