### ISSUE TITLE
Allow ignoring depleted resources of certain types (like oil)

### ISSUE THREAD

**Issue by dgw** [narc0tiq/YARM#64]
It's informative to have YARM keep an eye on oil deposits, but I find it less helpful that YARM absolutely insists on displaying minimum-yield oil fields all the time in (nearly unreadable—would be helped by #23) red text. I don't think removing the fields from YARM is the best solution, since it can still provide consumption info (and therefore, perspective on how much of the total oil intake is from "depleted" wells). But it's certainly not ideal to have to stare at them all the time.

I'm not really sure if it would be best to add a button to depleted resource patches in general that dismisses them from being displayed all the time, or a settings toggle for oil in particular… but some way of dismissing minimum-yield oil fields would be very welcome!

**Comment by dgw** [comment]
Actually, I went to verify my claim that YARM can provide consumption info from depleted wells, and it apparently cannot. My mistake. (That would be nice to handle, as well, though.)

**Comment by narc0tiq** [comment]
Yes, the problem is that you get basically no data from depleted infinite resources (except their position on the map, I guess). It's also not possible to derive consumption info from the oil entities alone, as they have no statistic to query -- they literally don't change at all once depleted.

There is actually a `config.lua` file that allows you to change what percentage YARM understands for depleted resources. Sadly, this never made it to the in-game settings UI (it would be a fairly trivial change, I just haven't looked at it at all; I accept patches!). You could use that to make them show as 10%, 100%, or any other percentage when empty (simple additive modifier to the calculated percent).

For my own purposes, I find the infinite resource tracking to be of marginal use, and would prefer to be tracking storage tanks (which can actually result in knowing the real production rate). Which is why I'm still working on https://github.com/narc0tiq/prodmon (last teaser: https://www.reddit.com/r/factorio/comments/6bptoi/teaser_production_monitor_mod/ is kind of old, I should probably make a new one).

**Comment by dgw** [comment]
Having thought about this some more during further play over the weekend, I think I'll just close this. There isn't really anything to be done about it, as I understand. And since there's no data to be obtained from depleted wells, there's no point in me keeping them in YARM once they hit 0%. They'll provide whatever oil they provide, and that's that. If I want more data, I'll keep an eye on prodmon, and meanwhile see if I can't devise some kind of circuit network solution (since in 0.15 pumpjacks can send the current oil mining rate to the circuit network).

Thanks for the in-depth (and fast!) response.
