### ISSUE TITLE
Desync?

### ISSUE THREAD

**Issue by abordoli** [narc0tiq/YARM#65]
I went through all of my mods today and narrowed down my MP desync issue to this one specific mod. Hopefully this is a known issue and I'm not alone in finding this.

If you would like for me to run further tests and give more details, let me know and I'd be happy to dig deeper. For the most part, I have other means of doing what this mod does but was taken in by the info displays and was a bit curious.

~B

**Comment by narc0tiq** [comment]
It's definitely not normal nor common; the last time I saw desyncs I could attribute to YARM was back in Factorio 0.12 (though I did have a false-positive report recently that turned out to be from EvoGUI -- linked to [this issue fixed in 0.15.23](https://forums.factorio.com/viewtopic.php?t=50055)).

Can you upload the desync report zip **from the client** to dropbox, or whatever, so I can take a peek? I'll also be interested in your specific mods and their versions, maybe a copy of your mods folder, too?

**Comment by narc0tiq** [comment]
It's been over a month, and I can't follow up on this without further data. Please reopen this issue if you think you've encountered the same desync again, or open a new one if you have any other troubles.

**Comment by abordoli** [comment]
Now worries. I've gotten over it and have found other mods to do the job. It also might have been another mod causing the desyncing and not yours so I'd assume all is OK.
Regards,
~B
