### ISSUE TITLE
Accidental softlock using viewer option of the mod 

### ISSUE THREAD

**Issue by Razinoid** [narc0tiq/YARM#74]
I have no idea how does the mod works, as me and my friend managed to softlock the game before even getting any grasp of the features and buttons the mod provides.

We are stuck what seems to be in view of the mining site with no character to control.
Facerolling the keyboard yields no results, there in also no inventory.

This state was achieved from what i suppose was in process of marking a mining site while using view option and then deleting the marking leaving us without a button to leave the state. 

We are using the version from https://mods.factorio.com/mods/Narc/YARM on a server.

**Comment by narc0tiq** [comment]
Sorry for the delay, I've been very sick and also very busy, and GIthub slipped my mind entirely.

That said, I can't really offer much -- you've managed to mess up in a very special way, and I can't imagine how you could fix it without using console commands.

Having established that, here are your options:
- give the remote camera fake player a resource monitor: `/c game.player.insert{name="resource-monitor"}`, and re-add the site you're watching. It may or may not then allow you to view the newly-recreated site, after which un-viewing it *may* return you to your character.
- go into god mode: `/c game.player.character = nil`, after which you can move around and find your real character. Once you do, use the YARM override to reset yourself into it:
    - mouse over the newly-created player
    - and do `/c remote.call("YARM", "reset_player", game.player.name)`.
- if you just want a new player character, you can spawn one (its inventory will be empty!): `/c local new_player 
= game.surfaces.nauvis.create_entity{name="player", position=game.player.position, force=game.forces.player} game.player.character = new_player`

Please try to be more careful around features like this in the future -- YARM does a lot of stupid stuff to provide remote viewing (indeed, I've been strongly considering removing the feature altogether since Factorio 0.15 hit), and I'm not very happy about it hiding the rename option behind a remote viewing.

...but I haven't been playing Factorio, so I haven't really touched YARM, either. I don't know when this will change, either.
