### ISSUE TITLE
Not able to remote View using bobs mods

### ISSUE THREAD

**Issue by GNRHOSH** [narc0tiq/YARM#85]
Issue is with the Bob's Character Mods as it is looking for the player to be in the original character, even though we are in our original body.  

The mod allows us to pick a class of character at the beginning of the game and then change later in the game somewhat freely.  

Easily repeatable in SP or MP with bobs full mod suite, build a YARM, setup some resources to monitor, and click on the icon to view the resources.

**Comment by narc0tiq** [comment]
I mean, it would be as simple as adding Bob's player character classes to the whitelist around https://github.com/narc0tiq/YARM/blob/7281ec5047d2ad9edb8f93a2f729a8b91094f255/resmon.lua#L773-L775 (ok, actually making it a _list_ instead of a single option would also be involved).

On the other hand, I'd love to just remove the remote viewing feature altogether (it's hiding the rename feature, and otherwise provides nothing that radar coverage doesn't also give you).

Not making any promises, I haven't played or modded Factorio in ages, but if you or someone wants to make me a pull request with either of those changes, I'll get it merged in.

**Comment by narc0tiq** [comment]
Fixed in v0.8 by removing the fake player entirely. Remote viewing is now actual remote viewing (map/zoom to world).
